// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BedManagementService.proto

package cw.BedManagementService;

public interface BedAssignmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BedManagementService.BedAssignmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bed_id = 1;</code>
   */
  int getBedId();

  /**
   * <code>string patient_name = 2;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();
}
