// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BedManagementService.proto

package cw.BedManagementService;

/**
 * Protobuf type {@code BedManagementService.BedAssignmentResponse}
 */
public  final class BedAssignmentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BedManagementService.BedAssignmentResponse)
    BedAssignmentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BedAssignmentResponse.newBuilder() to construct.
  private BedAssignmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BedAssignmentResponse() {
    success_ = false;
    assignedPatientName_ = "";
    bedId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BedAssignmentResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assignedPatientName_ = s;
            break;
          }
          case 24: {

            bedId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cw.BedManagementService.BedProto.internal_static_BedManagementService_BedAssignmentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cw.BedManagementService.BedProto.internal_static_BedManagementService_BedAssignmentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cw.BedManagementService.BedAssignmentResponse.class, cw.BedManagementService.BedAssignmentResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int ASSIGNED_PATIENT_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object assignedPatientName_;
  /**
   * <code>string assigned_patient_name = 2;</code>
   */
  public java.lang.String getAssignedPatientName() {
    java.lang.Object ref = assignedPatientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignedPatientName_ = s;
      return s;
    }
  }
  /**
   * <code>string assigned_patient_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssignedPatientNameBytes() {
    java.lang.Object ref = assignedPatientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignedPatientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BED_ID_FIELD_NUMBER = 3;
  private int bedId_;
  /**
   * <code>int32 bed_id = 3;</code>
   */
  public int getBedId() {
    return bedId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!getAssignedPatientNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assignedPatientName_);
    }
    if (bedId_ != 0) {
      output.writeInt32(3, bedId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!getAssignedPatientNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assignedPatientName_);
    }
    if (bedId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, bedId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cw.BedManagementService.BedAssignmentResponse)) {
      return super.equals(obj);
    }
    cw.BedManagementService.BedAssignmentResponse other = (cw.BedManagementService.BedAssignmentResponse) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && getAssignedPatientName()
        .equals(other.getAssignedPatientName());
    result = result && (getBedId()
        == other.getBedId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + ASSIGNED_PATIENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedPatientName().hashCode();
    hash = (37 * hash) + BED_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBedId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cw.BedManagementService.BedAssignmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cw.BedManagementService.BedAssignmentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BedManagementService.BedAssignmentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BedManagementService.BedAssignmentResponse)
      cw.BedManagementService.BedAssignmentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cw.BedManagementService.BedProto.internal_static_BedManagementService_BedAssignmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cw.BedManagementService.BedProto.internal_static_BedManagementService_BedAssignmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cw.BedManagementService.BedAssignmentResponse.class, cw.BedManagementService.BedAssignmentResponse.Builder.class);
    }

    // Construct using BedManagementService.BedAssignmentResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      assignedPatientName_ = "";

      bedId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cw.BedManagementService.BedProto.internal_static_BedManagementService_BedAssignmentResponse_descriptor;
    }

    @java.lang.Override
    public cw.BedManagementService.BedAssignmentResponse getDefaultInstanceForType() {
      return cw.BedManagementService.BedAssignmentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cw.BedManagementService.BedAssignmentResponse build() {
      cw.BedManagementService.BedAssignmentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cw.BedManagementService.BedAssignmentResponse buildPartial() {
      cw.BedManagementService.BedAssignmentResponse result = new cw.BedManagementService.BedAssignmentResponse(this);
      result.success_ = success_;
      result.assignedPatientName_ = assignedPatientName_;
      result.bedId_ = bedId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cw.BedManagementService.BedAssignmentResponse) {
        return mergeFrom((cw.BedManagementService.BedAssignmentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cw.BedManagementService.BedAssignmentResponse other) {
      if (other == cw.BedManagementService.BedAssignmentResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getAssignedPatientName().isEmpty()) {
        assignedPatientName_ = other.assignedPatientName_;
        onChanged();
      }
      if (other.getBedId() != 0) {
        setBedId(other.getBedId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cw.BedManagementService.BedAssignmentResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cw.BedManagementService.BedAssignmentResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object assignedPatientName_ = "";
    /**
     * <code>string assigned_patient_name = 2;</code>
     */
    public java.lang.String getAssignedPatientName() {
      java.lang.Object ref = assignedPatientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignedPatientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assigned_patient_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssignedPatientNameBytes() {
      java.lang.Object ref = assignedPatientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignedPatientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assigned_patient_name = 2;</code>
     */
    public Builder setAssignedPatientName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignedPatientName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_patient_name = 2;</code>
     */
    public Builder clearAssignedPatientName() {
      
      assignedPatientName_ = getDefaultInstance().getAssignedPatientName();
      onChanged();
      return this;
    }
    /**
     * <code>string assigned_patient_name = 2;</code>
     */
    public Builder setAssignedPatientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignedPatientName_ = value;
      onChanged();
      return this;
    }

    private int bedId_ ;
    /**
     * <code>int32 bed_id = 3;</code>
     */
    public int getBedId() {
      return bedId_;
    }
    /**
     * <code>int32 bed_id = 3;</code>
     */
    public Builder setBedId(int value) {
      
      bedId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bed_id = 3;</code>
     */
    public Builder clearBedId() {
      
      bedId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BedManagementService.BedAssignmentResponse)
  }

  // @@protoc_insertion_point(class_scope:BedManagementService.BedAssignmentResponse)
  private static final cw.BedManagementService.BedAssignmentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cw.BedManagementService.BedAssignmentResponse();
  }

  public static cw.BedManagementService.BedAssignmentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BedAssignmentResponse>
      PARSER = new com.google.protobuf.AbstractParser<BedAssignmentResponse>() {
    @java.lang.Override
    public BedAssignmentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BedAssignmentResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BedAssignmentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BedAssignmentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cw.BedManagementService.BedAssignmentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

