// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BedManagementService.proto

package cw.BedManagementService;

public final class BedProto {
  private BedProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_HospitalBedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_HospitalBedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_HospitalBedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_HospitalBedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_BedAssignmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_BedAssignmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_BedAssignmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_BedAssignmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_CleanerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_CleanerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BedManagementService_CleanerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BedManagementService_CleanerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032BedManagementService.proto\022\024BedManagem" +
      "entService\"$\n\022HospitalBedRequest\022\016\n\006bed_" +
      "id\030\001 \001(\005\"8\n\023HospitalBedResponse\022\021\n\tavail" +
      "able\030\001 \001(\010\022\016\n\006bed_id\030\002 \001(\005\"<\n\024BedAssignm" +
      "entRequest\022\016\n\006bed_id\030\001 \001(\005\022\024\n\014patient_na" +
      "me\030\002 \001(\t\"W\n\025BedAssignmentResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\035\n\025assigned_patient_name\030\002 \001(" +
      "\t\022\016\n\006bed_id\030\003 \001(\005\"\036\n\016CleanerRequest\022\014\n\004n" +
      "ame\030\001 \001(\t\"\"\n\017CleanerResponse\022\017\n\007message\030" +
      "\001 \001(\t2\317\002\n\022HospitalBedService\022q\n\024checkBed" +
      "Availability\022(.BedManagementService.Hosp" +
      "italBedRequest\032).BedManagementService.Ho" +
      "spitalBedResponse\"\000(\0010\001\022h\n\tassignBed\022*.B" +
      "edManagementService.BedAssignmentRequest" +
      "\032+.BedManagementService.BedAssignmentRes" +
      "ponse\"\000(\001\022\\\n\013giveCleaner\022$.BedManagement" +
      "Service.CleanerRequest\032%.BedManagementSe" +
      "rvice.CleanerResponse\"\000B\"\n\024BedManagement" +
      "ServiceB\010BedProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BedManagementService_HospitalBedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BedManagementService_HospitalBedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_HospitalBedRequest_descriptor,
        new java.lang.String[] { "BedId", });
    internal_static_BedManagementService_HospitalBedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BedManagementService_HospitalBedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_HospitalBedResponse_descriptor,
        new java.lang.String[] { "Available", "BedId", });
    internal_static_BedManagementService_BedAssignmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BedManagementService_BedAssignmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_BedAssignmentRequest_descriptor,
        new java.lang.String[] { "BedId", "PatientName", });
    internal_static_BedManagementService_BedAssignmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BedManagementService_BedAssignmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_BedAssignmentResponse_descriptor,
        new java.lang.String[] { "Success", "AssignedPatientName", "BedId", });
    internal_static_BedManagementService_CleanerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BedManagementService_CleanerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_CleanerRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_BedManagementService_CleanerResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BedManagementService_CleanerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BedManagementService_CleanerResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
