// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BedManagementService.proto

package cw.BedManagementService;

public interface HospitalBedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BedManagementService.HospitalBedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bed_id = 1;</code>
   */
  int getBedId();
}
