// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BedManagementService.proto

package cw.BedManagementService;

public interface HospitalBedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BedManagementService.HospitalBedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   */
  boolean getAvailable();

  /**
   * <code>int32 bed_id = 2;</code>
   */
  int getBedId();
}
