// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public interface AllRoomsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomTempService.AllRoomsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .RoomTempService.RoomTemp rooms = 1;</code>
   */
  java.util.List<cw.RoomTempService.RoomTemp> 
      getRoomsList();
  /**
   * <code>repeated .RoomTempService.RoomTemp rooms = 1;</code>
   */
  cw.RoomTempService.RoomTemp getRooms(int index);
  /**
   * <code>repeated .RoomTempService.RoomTemp rooms = 1;</code>
   */
  int getRoomsCount();
  /**
   * <code>repeated .RoomTempService.RoomTemp rooms = 1;</code>
   */
  java.util.List<? extends cw.RoomTempService.RoomTempOrBuilder> 
      getRoomsOrBuilderList();
  /**
   * <code>repeated .RoomTempService.RoomTemp rooms = 1;</code>
   */
  cw.RoomTempService.RoomTempOrBuilder getRoomsOrBuilder(
      int index);
}
