// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public interface RoomTempOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomTempService.RoomTemp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room_number = 1;</code>
   */
  int getRoomNumber();

  /**
   * <code>string temperature = 2;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
