// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public final class RoomTempServiceProto {
  private RoomTempServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_SetTempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_SetTempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_SetTempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_SetTempResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034RoomTemperatureService.proto\022\017RoomTemp" +
      "Service\"\"\n\013TempRequest\022\023\n\013room_number\030\001 " +
      "\001(\005\"#\n\014TempResponse\022\023\n\013temperature\030\001 \001(\t" +
      "\">\n\016SetTempRequest\022\023\n\013room_number\030\001 \001(\005\022" +
      "\027\n\017new_temperature\030\002 \001(\t\"!\n\017SetTempRespo" +
      "nse\022\016\n\006status\030\001 \001(\t2\247\001\n\013Temperature\022H\n\007G" +
      "etTemp\022\034.RoomTempService.TempRequest\032\035.R" +
      "oomTempService.TempResponse\"\000\022N\n\007SetTemp" +
      "\022\037.RoomTempService.SetTempRequest\032 .Room" +
      "TempService.SetTempResponse\"\000B)\n\017RoomTem" +
      "pServiceB\024RoomTempServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomTempService_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomTempService_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_TempRequest_descriptor,
        new java.lang.String[] { "RoomNumber", });
    internal_static_RoomTempService_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomTempService_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_TempResponse_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_RoomTempService_SetTempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RoomTempService_SetTempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_SetTempRequest_descriptor,
        new java.lang.String[] { "RoomNumber", "NewTemperature", });
    internal_static_RoomTempService_SetTempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RoomTempService_SetTempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_SetTempResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
