// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomTempService.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
