// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomTempService.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
