// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public final class TemperatureProto {
  private TemperatureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_SetTempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_SetTempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_TempReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_TempReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_RoomTemp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_RoomTemp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTempService_AllRoomsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTempService_AllRoomsReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034RoomTemperatureService.proto\022\017RoomTemp" +
      "Service\":\n\016SetTempRequest\022\023\n\013room_number" +
      "\030\001 \001(\005\022\023\n\013temperature\030\002 \001(\t\"\033\n\013TempReque" +
      "st\022\014\n\004name\030\001 \001(\t\"\034\n\tTempReply\022\017\n\007message" +
      "\030\001 \001(\t\"4\n\010RoomTemp\022\023\n\013room_number\030\001 \001(\005\022" +
      "\023\n\013temperature\030\002 \001(\t\"9\n\rAllRoomsReply\022(\n" +
      "\005rooms\030\001 \003(\0132\031.RoomTempService.RoomTemp2" +
      "\356\001\n\013Temperature\022F\n\010GiveTemp\022\034.RoomTempSe" +
      "rvice.TempRequest\032\032.RoomTempService.Temp" +
      "Reply\"\000\022H\n\007SetTemp\022\037.RoomTempService.Set" +
      "TempRequest\032\032.RoomTempService.TempReply\"" +
      "\000\022M\n\013GetAllRooms\022\034.RoomTempService.TempR" +
      "equest\032\036.RoomTempService.AllRoomsReply\"\000" +
      "B%\n\017RoomTempServiceB\020TemperatureProtoP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomTempService_SetTempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomTempService_SetTempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_SetTempRequest_descriptor,
        new java.lang.String[] { "RoomNumber", "Temperature", });
    internal_static_RoomTempService_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomTempService_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_TempRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_RoomTempService_TempReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RoomTempService_TempReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_TempReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_RoomTempService_RoomTemp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RoomTempService_RoomTemp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_RoomTemp_descriptor,
        new java.lang.String[] { "RoomNumber", "Temperature", });
    internal_static_RoomTempService_AllRoomsReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RoomTempService_AllRoomsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTempService_AllRoomsReply_descriptor,
        new java.lang.String[] { "Rooms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
