// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomTemperatureService.proto

package cw.RoomTempService;

public interface TempReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomTempService.TempReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
