// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

public interface AlertConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMonitoringService.AlertConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
