// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

/**
 * Protobuf type {@code HealthMonitoringService.AllVitalsReply}
 */
public  final class AllVitalsReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HealthMonitoringService.AllVitalsReply)
    AllVitalsReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllVitalsReply.newBuilder() to construct.
  private AllVitalsReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllVitalsReply() {
    vitalSignName_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllVitalsReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              vitalSignName_ = new java.util.ArrayList<cw.HealthMonitoringService.VitalSigns>();
              mutable_bitField0_ |= 0x00000001;
            }
            vitalSignName_.add(
                input.readMessage(cw.HealthMonitoringService.VitalSigns.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        vitalSignName_ = java.util.Collections.unmodifiableList(vitalSignName_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cw.HealthMonitoringService.MonitoringProto.internal_static_HealthMonitoringService_AllVitalsReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cw.HealthMonitoringService.MonitoringProto.internal_static_HealthMonitoringService_AllVitalsReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cw.HealthMonitoringService.AllVitalsReply.class, cw.HealthMonitoringService.AllVitalsReply.Builder.class);
  }

  public static final int VITALSIGNNAME_FIELD_NUMBER = 1;
  private java.util.List<cw.HealthMonitoringService.VitalSigns> vitalSignName_;
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  public java.util.List<cw.HealthMonitoringService.VitalSigns> getVitalSignNameList() {
    return vitalSignName_;
  }
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  public java.util.List<? extends cw.HealthMonitoringService.VitalSignsOrBuilder> 
      getVitalSignNameOrBuilderList() {
    return vitalSignName_;
  }
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  public int getVitalSignNameCount() {
    return vitalSignName_.size();
  }
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  public cw.HealthMonitoringService.VitalSigns getVitalSignName(int index) {
    return vitalSignName_.get(index);
  }
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  public cw.HealthMonitoringService.VitalSignsOrBuilder getVitalSignNameOrBuilder(
      int index) {
    return vitalSignName_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < vitalSignName_.size(); i++) {
      output.writeMessage(1, vitalSignName_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < vitalSignName_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, vitalSignName_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cw.HealthMonitoringService.AllVitalsReply)) {
      return super.equals(obj);
    }
    cw.HealthMonitoringService.AllVitalsReply other = (cw.HealthMonitoringService.AllVitalsReply) obj;

    boolean result = true;
    result = result && getVitalSignNameList()
        .equals(other.getVitalSignNameList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVitalSignNameCount() > 0) {
      hash = (37 * hash) + VITALSIGNNAME_FIELD_NUMBER;
      hash = (53 * hash) + getVitalSignNameList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cw.HealthMonitoringService.AllVitalsReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cw.HealthMonitoringService.AllVitalsReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HealthMonitoringService.AllVitalsReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HealthMonitoringService.AllVitalsReply)
      cw.HealthMonitoringService.AllVitalsReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cw.HealthMonitoringService.MonitoringProto.internal_static_HealthMonitoringService_AllVitalsReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cw.HealthMonitoringService.MonitoringProto.internal_static_HealthMonitoringService_AllVitalsReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cw.HealthMonitoringService.AllVitalsReply.class, cw.HealthMonitoringService.AllVitalsReply.Builder.class);
    }

    // Construct using HealthMonitoringService.AllVitalsReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVitalSignNameFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (vitalSignNameBuilder_ == null) {
        vitalSignName_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        vitalSignNameBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cw.HealthMonitoringService.MonitoringProto.internal_static_HealthMonitoringService_AllVitalsReply_descriptor;
    }

    @java.lang.Override
    public cw.HealthMonitoringService.AllVitalsReply getDefaultInstanceForType() {
      return cw.HealthMonitoringService.AllVitalsReply.getDefaultInstance();
    }

    @java.lang.Override
    public cw.HealthMonitoringService.AllVitalsReply build() {
      cw.HealthMonitoringService.AllVitalsReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cw.HealthMonitoringService.AllVitalsReply buildPartial() {
      cw.HealthMonitoringService.AllVitalsReply result = new cw.HealthMonitoringService.AllVitalsReply(this);
      int from_bitField0_ = bitField0_;
      if (vitalSignNameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          vitalSignName_ = java.util.Collections.unmodifiableList(vitalSignName_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vitalSignName_ = vitalSignName_;
      } else {
        result.vitalSignName_ = vitalSignNameBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cw.HealthMonitoringService.AllVitalsReply) {
        return mergeFrom((cw.HealthMonitoringService.AllVitalsReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cw.HealthMonitoringService.AllVitalsReply other) {
      if (other == cw.HealthMonitoringService.AllVitalsReply.getDefaultInstance()) return this;
      if (vitalSignNameBuilder_ == null) {
        if (!other.vitalSignName_.isEmpty()) {
          if (vitalSignName_.isEmpty()) {
            vitalSignName_ = other.vitalSignName_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVitalSignNameIsMutable();
            vitalSignName_.addAll(other.vitalSignName_);
          }
          onChanged();
        }
      } else {
        if (!other.vitalSignName_.isEmpty()) {
          if (vitalSignNameBuilder_.isEmpty()) {
            vitalSignNameBuilder_.dispose();
            vitalSignNameBuilder_ = null;
            vitalSignName_ = other.vitalSignName_;
            bitField0_ = (bitField0_ & ~0x00000001);
            vitalSignNameBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVitalSignNameFieldBuilder() : null;
          } else {
            vitalSignNameBuilder_.addAllMessages(other.vitalSignName_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cw.HealthMonitoringService.AllVitalsReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cw.HealthMonitoringService.AllVitalsReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cw.HealthMonitoringService.VitalSigns> vitalSignName_ =
      java.util.Collections.emptyList();
    private void ensureVitalSignNameIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        vitalSignName_ = new java.util.ArrayList<cw.HealthMonitoringService.VitalSigns>(vitalSignName_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cw.HealthMonitoringService.VitalSigns, cw.HealthMonitoringService.VitalSigns.Builder, cw.HealthMonitoringService.VitalSignsOrBuilder> vitalSignNameBuilder_;

    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public java.util.List<cw.HealthMonitoringService.VitalSigns> getVitalSignNameList() {
      if (vitalSignNameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vitalSignName_);
      } else {
        return vitalSignNameBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public int getVitalSignNameCount() {
      if (vitalSignNameBuilder_ == null) {
        return vitalSignName_.size();
      } else {
        return vitalSignNameBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public cw.HealthMonitoringService.VitalSigns getVitalSignName(int index) {
      if (vitalSignNameBuilder_ == null) {
        return vitalSignName_.get(index);
      } else {
        return vitalSignNameBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder setVitalSignName(
        int index, cw.HealthMonitoringService.VitalSigns value) {
      if (vitalSignNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalSignNameIsMutable();
        vitalSignName_.set(index, value);
        onChanged();
      } else {
        vitalSignNameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder setVitalSignName(
        int index, cw.HealthMonitoringService.VitalSigns.Builder builderForValue) {
      if (vitalSignNameBuilder_ == null) {
        ensureVitalSignNameIsMutable();
        vitalSignName_.set(index, builderForValue.build());
        onChanged();
      } else {
        vitalSignNameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder addVitalSignName(cw.HealthMonitoringService.VitalSigns value) {
      if (vitalSignNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalSignNameIsMutable();
        vitalSignName_.add(value);
        onChanged();
      } else {
        vitalSignNameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder addVitalSignName(
        int index, cw.HealthMonitoringService.VitalSigns value) {
      if (vitalSignNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalSignNameIsMutable();
        vitalSignName_.add(index, value);
        onChanged();
      } else {
        vitalSignNameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder addVitalSignName(
        cw.HealthMonitoringService.VitalSigns.Builder builderForValue) {
      if (vitalSignNameBuilder_ == null) {
        ensureVitalSignNameIsMutable();
        vitalSignName_.add(builderForValue.build());
        onChanged();
      } else {
        vitalSignNameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder addVitalSignName(
        int index, cw.HealthMonitoringService.VitalSigns.Builder builderForValue) {
      if (vitalSignNameBuilder_ == null) {
        ensureVitalSignNameIsMutable();
        vitalSignName_.add(index, builderForValue.build());
        onChanged();
      } else {
        vitalSignNameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder addAllVitalSignName(
        java.lang.Iterable<? extends cw.HealthMonitoringService.VitalSigns> values) {
      if (vitalSignNameBuilder_ == null) {
        ensureVitalSignNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vitalSignName_);
        onChanged();
      } else {
        vitalSignNameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder clearVitalSignName() {
      if (vitalSignNameBuilder_ == null) {
        vitalSignName_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        vitalSignNameBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public Builder removeVitalSignName(int index) {
      if (vitalSignNameBuilder_ == null) {
        ensureVitalSignNameIsMutable();
        vitalSignName_.remove(index);
        onChanged();
      } else {
        vitalSignNameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public cw.HealthMonitoringService.VitalSigns.Builder getVitalSignNameBuilder(
        int index) {
      return getVitalSignNameFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public cw.HealthMonitoringService.VitalSignsOrBuilder getVitalSignNameOrBuilder(
        int index) {
      if (vitalSignNameBuilder_ == null) {
        return vitalSignName_.get(index);  } else {
        return vitalSignNameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public java.util.List<? extends cw.HealthMonitoringService.VitalSignsOrBuilder> 
         getVitalSignNameOrBuilderList() {
      if (vitalSignNameBuilder_ != null) {
        return vitalSignNameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vitalSignName_);
      }
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public cw.HealthMonitoringService.VitalSigns.Builder addVitalSignNameBuilder() {
      return getVitalSignNameFieldBuilder().addBuilder(
          cw.HealthMonitoringService.VitalSigns.getDefaultInstance());
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public cw.HealthMonitoringService.VitalSigns.Builder addVitalSignNameBuilder(
        int index) {
      return getVitalSignNameFieldBuilder().addBuilder(
          index, cw.HealthMonitoringService.VitalSigns.getDefaultInstance());
    }
    /**
     * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
     */
    public java.util.List<cw.HealthMonitoringService.VitalSigns.Builder> 
         getVitalSignNameBuilderList() {
      return getVitalSignNameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cw.HealthMonitoringService.VitalSigns, cw.HealthMonitoringService.VitalSigns.Builder, cw.HealthMonitoringService.VitalSignsOrBuilder> 
        getVitalSignNameFieldBuilder() {
      if (vitalSignNameBuilder_ == null) {
        vitalSignNameBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cw.HealthMonitoringService.VitalSigns, cw.HealthMonitoringService.VitalSigns.Builder, cw.HealthMonitoringService.VitalSignsOrBuilder>(
                vitalSignName_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        vitalSignName_ = null;
      }
      return vitalSignNameBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HealthMonitoringService.AllVitalsReply)
  }

  // @@protoc_insertion_point(class_scope:HealthMonitoringService.AllVitalsReply)
  private static final cw.HealthMonitoringService.AllVitalsReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cw.HealthMonitoringService.AllVitalsReply();
  }

  public static cw.HealthMonitoringService.AllVitalsReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllVitalsReply>
      PARSER = new com.google.protobuf.AbstractParser<AllVitalsReply>() {
    @java.lang.Override
    public AllVitalsReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllVitalsReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllVitalsReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllVitalsReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cw.HealthMonitoringService.AllVitalsReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

