// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

public interface AllVitalsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMonitoringService.AllVitalsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  java.util.List<cw.HealthMonitoringService.VitalSigns> 
      getVitalSignNameList();
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  cw.HealthMonitoringService.VitalSigns getVitalSignName(int index);
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  int getVitalSignNameCount();
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  java.util.List<? extends cw.HealthMonitoringService.VitalSignsOrBuilder> 
      getVitalSignNameOrBuilderList();
  /**
   * <code>repeated .HealthMonitoringService.VitalSigns VitalSignName = 1;</code>
   */
  cw.HealthMonitoringService.VitalSignsOrBuilder getVitalSignNameOrBuilder(
      int index);
}
