// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

public final class MonitoringProto {
  private MonitoringProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_PatientID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_PatientID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_PatientVitals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_PatientVitals_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_SafeVitalsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_SafeVitalsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_VitalSigns_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_VitalSigns_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_AllVitalsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_AllVitalsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthMonitoringService_AlertConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthMonitoringService_AlertConfirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035HealthMonitoringService.proto\022\027HealthM" +
      "onitoringService\"\027\n\tPatientID\022\n\n\002id\030\001 \001(" +
      "\t\"d\n\rPatientVitals\022\022\n\npatient_id\030\001 \001(\t\022\022" +
      "\n\nheart_rate\030\002 \001(\001\022\026\n\016blood_pressure\030\003 \001" +
      "(\001\022\023\n\013temperature\030\004 \001(\001\"!\n\021SafeVitalsReq" +
      "uest\022\014\n\004name\030\001 \001(\t\"6\n\nVitalSigns\022\025\n\rVita" +
      "lSignName\030\001 \001(\t\022\021\n\tSafeRange\030\002 \001(\t\"L\n\016Al" +
      "lVitalsReply\022:\n\rVitalSignName\030\001 \003(\0132#.He" +
      "althMonitoringService.VitalSigns\"$\n\021Aler" +
      "tConfirmation\022\017\n\007success\030\001 \001(\0102\303\002\n\027Healt" +
      "hMonitoringService\022^\n\020GetPatientVitals\022\"" +
      ".HealthMonitoringService.PatientID\032&.Hea" +
      "lthMonitoringService.PatientVitals\022b\n\014Al" +
      "ertDoctors\022&.HealthMonitoringService.Pat" +
      "ientVitals\032*.HealthMonitoringService.Ale" +
      "rtConfirmation\022d\n\rGetSafeVitals\022*.Health" +
      "MonitoringService.SafeVitalsRequest\032\'.He" +
      "althMonitoringService.AllVitalsReplyB,\n\027" +
      "HealthMonitoringServiceB\017MonitoringProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HealthMonitoringService_PatientID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HealthMonitoringService_PatientID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_PatientID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_HealthMonitoringService_PatientVitals_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HealthMonitoringService_PatientVitals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_PatientVitals_descriptor,
        new java.lang.String[] { "PatientId", "HeartRate", "BloodPressure", "Temperature", });
    internal_static_HealthMonitoringService_SafeVitalsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HealthMonitoringService_SafeVitalsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_SafeVitalsRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_HealthMonitoringService_VitalSigns_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HealthMonitoringService_VitalSigns_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_VitalSigns_descriptor,
        new java.lang.String[] { "VitalSignName", "SafeRange", });
    internal_static_HealthMonitoringService_AllVitalsReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_HealthMonitoringService_AllVitalsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_AllVitalsReply_descriptor,
        new java.lang.String[] { "VitalSignName", });
    internal_static_HealthMonitoringService_AlertConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HealthMonitoringService_AlertConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthMonitoringService_AlertConfirmation_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
