// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

public interface SafeVitalsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMonitoringService.SafeVitalsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
