// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMonitoringService.proto

package cw.HealthMonitoringService;

public interface VitalSignsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HealthMonitoringService.VitalSigns)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string VitalSignName = 1;</code>
   */
  java.lang.String getVitalSignName();
  /**
   * <code>string VitalSignName = 1;</code>
   */
  com.google.protobuf.ByteString
      getVitalSignNameBytes();

  /**
   * <code>string SafeRange = 2;</code>
   */
  java.lang.String getSafeRange();
  /**
   * <code>string SafeRange = 2;</code>
   */
  com.google.protobuf.ByteString
      getSafeRangeBytes();
}
